proyecto_turnero/core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('turnero/', HomeView.as_view(), name="home"),

    path('', include('turnero.urls', namespace='turnero')),
]

proyecto_turnero/turnero/urls.py
from django.urls import path
from .views import LoginFormView, TurneroRegisterView, TurneroOrderView, TurneroListBox1View, TurneroListBox2View, TurneroListBox3View, TurneroCheckView1, TurneroUpdateView1, TurneroDeleteView1, TurneroCheckView2, TurneroUpdateView2, TurneroDeleteView2, TurneroCheckView2, TurneroCheckView3, TurneroUpdateView3, TurneroDeleteView3

app_name="turnero"

urlpatterns = [
    
    path('',LoginFormView.as_view(), name="login"),
    path('login/', LoginFormView.as_view(), name='login'),
    path('registro/',TurneroRegisterView.as_view(), name="registro"),
    path('orden/', TurneroOrderView.as_view(), name="orden"),
    path('box1/', TurneroListBox1View.as_view(), name="box1"),
    path('box2/', TurneroListBox2View.as_view(), name="box2"),
    path('box3/', TurneroListBox3View.as_view(), name="box3"),

    path('<int:pk>/box1/atendido/', TurneroCheckView1.as_view(), name="atendidobox1"),
    path('<int:pk>/box1/update/', TurneroUpdateView1.as_view(), name="editarbox1"),
    path('<int:pk>/box1/delete/', TurneroDeleteView1.as_view(), name="eliminarbox1"),

    path('<int:pk>/box2/atendido/', TurneroCheckView2.as_view(), name="atendidobox2"),
    path('<int:pk>/box2/update/', TurneroUpdateView2.as_view(), name="editarbox2"),
    path('<int:pk>/box2/delete/', TurneroDeleteView2.as_view(), name="eliminarbox2"),

    path('<int:pk>/box3/atendido/', TurneroCheckView3.as_view(), name="atendidobox3"),
    path('<int:pk>/box3/update/', TurneroUpdateView3.as_view(), name="editarbox3"),
    path('<int:pk>/box3/delete/', TurneroDeleteView3.as_view(), name="eliminarbox3")

]

proyecto_turnero/turnero/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver


class Cliente(models.Model):
    PRIORIDAD_CHOICES = (
        (1, 'Alta'),
        (2, 'Media'),
        (3, 'Baja'),
    )
    BOXES_CHOICES = (
        (1, 'Box 1'),
        (2, 'Box 2'),
        (3, 'Box 3'),
    )

    nombre = models.CharField(max_length=100)
    cedula_ruc = models.CharField(max_length=20, unique=False)
    turno = models.AutoField(primary_key=True, unique=False)
    prioridad = models.IntegerField(choices=PRIORIDAD_CHOICES)
    servicios = models.IntegerField(choices=BOXES_CHOICES)
    fecha_hora = models.DateTimeField(auto_now_add=True)
    atendido = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre
    

proyecto_turnero/templates/turnero_edit.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>EDICION</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>


    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'turnero:login' %}">TURNERO</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'turnero:registro' %}">Registro</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'turnero:orden' %}">Orden</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"  href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Servicios
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'turnero:box1' %}">Box 1</a></li>
                      <li><a class="dropdown-item" href="#">Box 2</a></li>
                      <li><a class="dropdown-item" href="#">Box 3</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          
          <div class="container py order-1 -4 order-md-1">
            <div class="row">
                <h1>EDICION</h1>
                <div class="col-md-4 order-2 order-md-2">
                    <h2>CLIENTE</h2>
                    <div class="card">
                        <div class="card">
                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="id_nombre">Nombre o Razón Social:</label>
                                        <br>
                                        {{ form.nombre }}
                                        
                                    </div>
                                    <div class="form-group">
                                        <label for="id_cedula_ruc">C.I. o RUC:</label>
                                        <br>
                                        {{ form.cedula_ruc }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_prioridad">Nivel de Prioridad:</label>
                                        <br>
                                        {{ form.prioridad }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_servicios">Servicio:</label>
                                        <br>
                                        {{ form.servicios }}
                                    </div>
                                    <br>
                                    <button type="submit" class="btn btn-success btn-block text-white">Registrar</button>
                                </form>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
        
        <script src="" async defer></script>
        <script async src="https://cdn.jsdelivr.net/npm/es-module-shims@1/dist/es-module-shims.min.js" crossorigin="anonymous"></script>
        <script type="importmap">
        {
          "imports": {
            "@popperjs/core": "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js",
            "bootstrap": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.esm.min.js"
          }
        }
        </script>
        <script type="module">
          import * as bootstrap from 'bootstrap'
    
          new bootstrap.Popover(document.getElementById('popoverButton'))
        </script>
    </body>
</html>

proyecto_turnero/templates/turnero_listbox1.html
<!DOCTYPE html>
{% load static %}
<link rel="icon" href="img/logo-turnero.ico">

<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BOX 1</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>

    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'turnero:login' %}">TURNERO</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'turnero:registro' %}">Registro</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'turnero:orden' %}">Orden</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" aria-current="page"  href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Servicios
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item active" aria-current="page" href="{% url 'turnero:box1' %}">Box 1</a></li>
                      <li><a class="dropdown-item" href="{% url 'turnero:box2' %}">Box 2</a></li>
                      <li><a class="dropdown-item" href="{% url 'turnero:box3' %}">Box 3</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          
          <div class="container py-20 order-md-1">
            <div class="row">
              <h1>SERVICIOS</h1>
              <div class="col-md-12 order-1 order-md-2">
                <ul class="list-group">
                  <h2>BOX 1</h2>
                  <li class="list-group-item">
                    <div class="row">
                      <div class="col-md-2">
                        <strong>Turno:</strong>
                      </div>
                      <div class="col-md-2">
                        <strong>Nombre:</strong>
                      </div>
                      <div class="col-md-2">
                        <strong>C.I. o RUC:</strong>
                      </div>
                      <div class="col-md-2">
                        <strong>Prioridad:</strong>
                      </div>
                    </div>
                  </li>

                  {% for cliente in clientes_box1 %}
                  <li class="list-group-item">
                    <div class="row">
                      <div class="col-md-2">
                        {{ forloop.counter }}
                      </div>
                      <div class="col-md-2">
                        {{ cliente.nombre }}
                      </div>
                      <div class="col-md-2">
                        {{ cliente.cedula_ruc }}
                      </div>
                      <div class="col-md-2">
                        {{ cliente.prioridad }}
                      </div>
                      <div class="col-md-1">
                        <a href="{% url 'turnero:atendidobox1' cliente.pk %}" class="btn btn-sm btn-block btn-success text-white">Atendido</a>
                      </div>
                      <div class="col-md-1">
                        <a href="{% url 'turnero:editarbox1' cliente.pk %}" class="btn btn-sm btn-block btn-primary text-white">Editar</a>
                      </div>
                      <div class="col-md-1">
                        <a href="{% url 'turnero:eliminarbox1' cliente.pk %}" class="btn btn-sm btn-block btn-danger text-white">Eliminar</a>
                      </div>
                    </div>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        
        <script src="" async defer></script>
        <script async src="https://cdn.jsdelivr.net/npm/es-module-shims@1/dist/es-module-shims.min.js" crossorigin="anonymous"></script>
        <script type="importmap">
        {
          "imports": {
            "@popperjs/core": "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js",
            "bootstrap": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.esm.min.js"
          }
        }
        </script>
        <script type="module">
          import * as bootstrap from 'bootstrap'
    
          new bootstrap.Popover(document.getElementById('popoverButton'))
        </script>
        
    </body>
</html>

proyecto_turnero/templates/turnero_listbox2.html
<!DOCTYPE html>
{% load static %}
<link rel="icon" href="img/logo-turnero.ico">

<html>

    <head>
      
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BOX 2</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        
    </head>

    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'turnero:login' %}">TURNERO</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'turnero:registro' %}">Registro</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'turnero:orden' %}">Orden</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" aria-current="page"  href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Servicios
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'turnero:box1' %}">Box 1</a></li>
                      <li><a class="dropdown-item active" aria-current="page" href="{% url 'turnero:box2' %}">Box 2</a></li>
                      <li><a class="dropdown-item" href="{% url 'turnero:box3' %}">Box 3</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          
          <div class="container py-20 order-md-1">
            <div class="row">
              <h1>SERVICIOS</h1>
              <div class="col-md-12 order-1 order-md-2">
                <ul class="list-group">
                  <h2>BOX 2</h2>
                  <li class="list-group-item">
                    <div class="row">
                      <div class="col-md-2">
                        <strong>Turno:</strong>
                      </div>
                      <div class="col-md-2">
                        <strong>Nombre:</strong>
                      </div>
                      <div class="col-md-2">
                        <strong>C.I. o RUC:</strong>
                      </div>
                      <div class="col-md-2">
                        <strong>Prioridad:</strong>
                      </div>
                    </div>
                  </li>
                  
                  {% for cliente in clientes_box2 %}
                  <li class="list-group-item">
                    <div class="row">
                      <div class="col-md-2">
                        {{ forloop.counter }}
                      </div>
                      <div class="col-md-2">
                        {{ cliente.nombre }}
                      </div>
                      <div class="col-md-2">
                        {{ cliente.cedula_ruc }}
                      </div>
                      <div class="col-md-2">
                        {{ cliente.prioridad }}
                      </div>
                      <div class="col-md-1">
                        <a href="{% url 'turnero:atendidobox2' cliente.pk %}" class="btn btn-sm btn-block btn-success text-white">Atendido</a>
                      </div>
                      <div class="col-md-1">
                        <a href="{% url 'turnero:editarbox2' cliente.pk %}" class="btn btn-sm btn-block btn-primary text-white">Editar</a>
                      </div>
                      <div class="col-md-1">
                        <a href="{% url 'turnero:eliminarbox2' cliente.pk %}" class="btn btn-sm btn-block btn-danger text-white">Eliminar</a>
                      </div>
                    </div>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        
        <script src="" async defer></script>
        <script async src="https://cdn.jsdelivr.net/npm/es-module-shims@1/dist/es-module-shims.min.js" crossorigin="anonymous"></script>
        <script type="importmap">
        {
          "imports": {
            "@popperjs/core": "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js",
            "bootstrap": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.esm.min.js"
          }
        }
        </script>
        <script type="module">
          import * as bootstrap from 'bootstrap'
    
          new bootstrap.Popover(document.getElementById('popoverButton'))
        </script>
        
    </body>
</html>

proyecto_turnero/templates/turnero_listbox3.html
<!DOCTYPE html>
{% load static %}
<link rel="icon" href="img/logo-turnero.ico">

<html>

    <head>
      
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BOX 3</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        
    </head>

    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'turnero:login' %}">TURNERO</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'turnero:registro' %}">Registro</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'turnero:orden' %}">Orden</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" aria-current="page"  href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Servicios
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'turnero:box1' %}">Box 1</a></li>
                      <li><a class="dropdown-item" href="{% url 'turnero:box2' %}">Box 2</a></li>
                      <li><a class="dropdown-item active" aria-current="page" href="{% url 'turnero:box3' %}">Box 3</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          
          <div class="container py-20 order-md-1">
            <div class="row">
              <h1>SERVICIOS</h1>
              <div class="col-md-12 order-1 order-md-2">
                <ul class="list-group">
                  <h2>BOX 3</h2>
                  <li class="list-group-item">
                    <div class="row">
                      <div class="col-md-2">
                        <strong>Turno:</strong>
                      </div>
                      <div class="col-md-2">
                        <strong>Nombre:</strong>
                      </div>
                      <div class="col-md-2">
                        <strong>C.I. o RUC:</strong>
                      </div>
                      <div class="col-md-2">
                        <strong>Prioridad:</strong>
                      </div>
                    </div>
                  </li>
                  
                  {% for cliente in clientes_box3 %}
                  <li class="list-group-item">
                    <div class="row">
                      <div class="col-md-2">
                        {{ forloop.counter }}
                      </div>
                      <div class="col-md-2">
                        {{ cliente.nombre }}
                      </div>
                      <div class="col-md-2">
                        {{ cliente.cedula_ruc }}
                      </div>
                      <div class="col-md-2">
                        {{ cliente.prioridad }}
                      </div>
                      <div class="col-md-1">
                        <a href="{% url 'turnero:atendidobox3' cliente.pk %}" class="btn btn-sm btn-block btn-success text-white">Atendido</a>
                      </div>
                      <div class="col-md-1">
                        <a href="{% url 'turnero:editarbox3' cliente.pk %}" class="btn btn-sm btn-block btn-primary text-white">Editar</a>
                      </div>
                      <div class="col-md-1">
                        <a href="{% url 'turnero:eliminarbox3' cliente.pk %}" class="btn btn-sm btn-block btn-danger text-white">Eliminar</a>
                      </div>
                    </div>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        
        <script src="" async defer></script>
        <script async src="https://cdn.jsdelivr.net/npm/es-module-shims@1/dist/es-module-shims.min.js" crossorigin="anonymous"></script>
        <script type="importmap">
        {
          "imports": {
            "@popperjs/core": "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js",
            "bootstrap": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.esm.min.js"
          }
        }
        </script>
        <script type="module">
          import * as bootstrap from 'bootstrap'
    
          new bootstrap.Popover(document.getElementById('popoverButton'))
        </script>
        
    </body>
</html>

proyecto_turnero/templates/turnero_register.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>REGISTRO</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>


    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'turnero:login' %}">TURNERO</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'turnero:registro' %}">Registro</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'turnero:orden' %}">Orden</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"  href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Servicios
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'turnero:box1' %}">Box 1</a></li>
                      <li><a class="dropdown-item" href="#">Box 2</a></li>
                      <li><a class="dropdown-item" href="#">Box 3</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          
          <div class="container py order-1 -4 order-md-1">
            <div class="row">
                <h1>REGISTRO</h1>
                <div class="col-md-4 order-2 order-md-2">
                    <h2>CLIENTE</h2>
                    <div class="card">
                        <div class="card">
                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="id_nombre">Nombre o Razón Social:</label>
                                        <br>
                                        {{ form.nombre }}
                                        
                                    </div>
                                    <div class="form-group">
                                        <label for="id_cedula_ruc">C.I. o RUC:</label>
                                        <br>
                                        {{ form.cedula_ruc }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_prioridad">Nivel de Prioridad:</label>
                                        <br>
                                        {{ form.prioridad }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_servicios">Servicio:</label>
                                        <br>
                                        {{ form.servicios }}
                                    </div>
                                    <br>
                                    <button type="submit" class="btn btn-success btn-block text-white">Registrar</button>
                                </form>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
        
        <script src="" async defer></script>
        <script async src="https://cdn.jsdelivr.net/npm/es-module-shims@1/dist/es-module-shims.min.js" crossorigin="anonymous"></script>
        <script type="importmap">
        {
          "imports": {
            "@popperjs/core": "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js",
            "bootstrap": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.esm.min.js"
          }
        }
        </script>
        <script type="module">
          import * as bootstrap from 'bootstrap'
    
          new bootstrap.Popover(document.getElementById('popoverButton'))
        </script>
    </body>
</html>